### ISSUE TITLE
Manually installation Failure

### ISSUE THREAD

**Issue by mirkoperillo** [telefonicaid/fiware-cosmos-platform#2]
I'm following the guide to install manually cosmos.

I created the 5 centos machines used by cosmos and I followed all instructions.

When I execute on my slaves the `puppet apply` command, puppet.err log presents some errors.

All the errors refer to web repository not reachable (130.206.81.65 machine seems not reachable).

The common.yaml presents a lot of configurations referring to this remote machine

```
ambari::params::repo_url: 'http://130.206.81.65/cosmos/ambari/'
ambari::params::jce_url: 'http://130.206.81.65/cosmos/java/jce_policy-6.zip'
...
...

```

Another question about this.

In guide there's a section where it must configure a local repo for ambari e java in every machine,
but then puppet seems to download them from a remote one.
What's the meaning of local repo ?

Waiting for some hint to have a working cosmos platform...

**Comment by frbattid** [comment]
Mirko, try again. The repo server was down for any reason.

**Comment by mirkoperillo** [comment]
Hi,

good, now I'm able to reach repo so I'm moving forward with installation

thanks.
I close the issue
